version: '3'
services:
  web:
    build: 
      # where from we want to build from in this case its current directory
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      #map current folder outside of the container to inside of the container
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]